/*Autogenerated by LayerLoaderConfigurator for dev context*/
define(
{
  "queryMmaLayer": "https://gemini.at.geoplan.ufl.edu/arcgis/rest/services/oem_services/Query_MMA_Dev/MapServer/0",
  "queryDraftLayer": "https://gemini.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/Query_Drafts_Dev/MapServer/0",
  "previouslyReviewedProjectsService": "https://gemini.at.geoplan.ufl.edu/arcgis/rest/services/oem_services/Previously_Reviewed_Dev/MapServer",
  "currentlyInReviewProjectsService": "https://gemini.at.geoplan.ufl.edu/arcgis/rest/services/oem_services/ETAT_Review_Dev/MapServer",
  "draftProjectsService": "https://gemini.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/Draft_Projects_Dev/MapServer",
  "aoiLayers": {
    "analysisAreaBuffer": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/AOIDEV_INPUT/FeatureServer/4",
    "point": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/AOIDEV_INPUT/FeatureServer/1",
    "polyline": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/AOIDEV_INPUT/FeatureServer/2",
    "polygon": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/AOIDEV_INPUT/FeatureServer/3"
  },
  "estProjectLayers": {
    "point": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/ESTDEV_INPUT/FeatureServer/0",
    "polyline": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/ESTDEV_INPUT/FeatureServer/1",
    "polygon": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/ESTDEV_INPUT/FeatureServer/2"
  }
}
);
