/*Autogenerated by LayerLoaderConfigurator for dev context*/
define(
{
  "queryMmaLayer": "https://leo.at.geoplan.ufl.edu/arcgis/rest/services/oem_services/QUERY_MMA_DEV/MapServer/0",
  "queryDraftLayer": "https://leo.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/QUERY_DRAFTS_DEV/MapServer/0",
  "queryRegionsLayer": "https://capricorn.at.geoplan.ufl.edu/arcgis/rest/services/etdm_services/QUERY_REGIONS/MapServer/0",
  "previouslyReviewedProjectsService": "https://leo.at.geoplan.ufl.edu/arcgis/rest/services/oem_services/PREVIOUSLY_REVIEWED_DEV/MapServer",
  "currentlyInReviewProjectsService": "https://leo.at.geoplan.ufl.edu/arcgis/rest/services/oem_services/ETAT_REVIEW_DEV/MapServer",
  "eliminatedProjectsService": "https://leo.at.geoplan.ufl.edu/arcgis/rest/services/oem_services/ELIMINATED_DEV/MapServer",
  "draftProjectsService": "https://leo.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/DRAFT_PROJECTS_DEV/MapServer",
  "rciBasemapService": "https://pisces.at.geoplan.ufl.edu/arcgis/rest/services/etdm_services/RCI_Base/MapServer",
  "aoiLayers": {
    "analysisAreaBuffer": "https://leo.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/AOIDEV_INPUT/FeatureServer/4",
    "point": "https://leo.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/AOIDEV_INPUT/FeatureServer/1",
    "polyline": "https://leo.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/AOIDEV_INPUT/FeatureServer/2",
    "polygon": "https://leo.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/AOIDEV_INPUT/FeatureServer/3"
  },
  "estProjectLayers": {
    "point": "https://leo.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/ESTDEV_INPUT_LAYERS/FeatureServer/0",
    "polyline": "https://leo.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/ESTDEV_INPUT_LAYERS/FeatureServer/1",
    "polygon": "https://leo.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/ESTDEV_INPUT_LAYERS/FeatureServer/2"
  }
}
);
