/*Autogenerated by LayerLoaderConfigurator for prod context*/
define(
{
  "queryMmaLayer": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/OEM_Map_Services/Query_MMA_Prod/MapServer/0",
  "queryDraftLayer": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/Query_Drafts_Prod/MapServer//0",
  "previouslyReviewedProjectsService": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/OEM_Map_Services/Previously_Reviewed_Prod/MapServer",
  "currentlyInReviewProjectsService": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/OEM_Map_Services/ETAT_Review_Prod/MapServer",
  "draftProjectsService": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/Draft_Projects_Prod/MapServer/",
  "aoiLayers": {
    "analysisAreaBuffer": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/AOIPROD_INPUT/FeatureServer/3",
    "point": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/AOIPROD_INPUT/FeatureServer/0",
    "polyline": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/AOIPROD_INPUT/FeatureServer/1",
    "polygon": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/AOIPROD_INPUT/FeatureServer/2"
  },
  "estProjectLayers": {
    "point": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/ESTPROD_INPUT/FeatureServer/0",
    "polyline": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/ESTPROD_INPUT/FeatureServer/1",
    "polygon": "https://aquarius.at.geoplan.ufl.edu/arcgis/rest/services/secure_services/ESTPROD_INPUT/FeatureServer/2"
  }
}
);
